[workspace]
authors = ["Wiktor Jurkiewicz <watjurk@gmail.com>", "Augustas Paliulis"]
channels = ["conda-forge", "pytorch"]
name = "project"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "python ./src/main.py"

[dependencies]
transformers = ">=4.52.4,<5"
pytorch = ">=2.7.0,<3"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.0.0,<7"
scikit-learn = ">=1.2.0,<2"
matplotlib = ">=3.7.0,<4"
seaborn = ">=0.12.0,<0.14"
xgboost = ">=2.0.0,<4"
pip = ">=25.1.1,<26"
nltk = ">=3.9.1,<4"
spacy = ">=3.8.6,<4"
python = ">=3.12.10,<3.13"
numpy = ">=2.2.6,<3"

[pypi-dependencies]
hf-xet = ">=1.1.2, <2"
